mapinfos = [
  { "id" => 2, "parent" => 0, "name" => "Title Map" },
  { "id" => 1, "parent" => 0, "name" => "Test maps" },
  { "id" => 6, "parent" => 0, "name" => "Main Village" },
  { "id" => 9, "parent" => 0, "name" => "East Village Entrance" },
  { "id" => 3, "parent" => 0, "name" => "Mayor House" },
  { "id" => 8, "parent" => 0, "name" => "West Lake" },
  { "id" => 39, "parent" => 0, "name" => "North Village Entrance" },
  { "id" => 44, "parent" => 0, "name" => "South Village Entrance" },
  { "id" => 53, "parent" => 1, "name" => "Test maps" },
  { "id" => 4, "parent" => 2, "name" => "Title" },
  { "id" => 24, "parent" => 2, "name" => "Blank Map" },
  { "id" => 21, "parent" => 3, "name" => "Mayor's House" },
  { "id" => 29, "parent" => 5, "name" => "Cave 1" },
  { "id" => 30, "parent" => 5, "name" => "Cave 2" },
  { "id" => 17, "parent" => 6, "name" => "Residence 1" },
  { "id" => 18, "parent" => 6, "name" => "Residence 2" },
  { "id" => 19, "parent" => 6, "name" => "Residence 3" },
  { "id" => 7, "parent" => 6, "name" => "West Village" },
  { "id" => 11, "parent" => 6, "name" => "North Village" },
  { "id" => 12, "parent" => 6, "name" => "South Village" },
  { "id" => 54, "parent" => 6, "name" => "Item Shop" },
  { "id" => 14, "parent" => 7, "name" => "Yuuki's House" },
  { "id" => 15, "parent" => 7, "name" => "West Inn F1" },
  { "id" => 16, "parent" => 7, "name" => "West Inn F2" },
  { "id" => 32, "parent" => 8, "name" => "West Forest 1" },
  { "id" => 33, "parent" => 8, "name" => "West Forest 2" },
  { "id" => 34, "parent" => 8, "name" => "West Forest 3" },
  { "id" => 37, "parent" => 8, "name" => "West Forest 4" },
  { "id" => 35, "parent" => 8, "name" => "West Forest 5" },
  { "id" => 10, "parent" => 9, "name" => "East Road" },
  { "id" => 25, "parent" => 10, "name" => "East Forest 1" },
  { "id" => 26, "parent" => 10, "name" => "East Forest 2" },
  { "id" => 28, "parent" => 10, "name" => "East Forest 3" },
  { "id" => 27, "parent" => 10, "name" => "East Forest 4" },
  { "id" => 23, "parent" => 11, "name" => "Farmer's House" },
  { "id" => 5, "parent" => 11, "name" => "Cave" },
  { "id" => 22, "parent" => 12, "name" => "Beggar's House" },
  { "id" => 13, "parent" => 12, "name" => "South-East Tree" },
  { "id" => 31, "parent" => 15, "name" => "Dining Room" },
  { "id" => 36, "parent" => 34, "name" => "Bandit Hideout" },
  { "id" => 38, "parent" => 36, "name" => "Bandit House" },
  { "id" => 40, "parent" => 39, "name" => "North Forest 1" },
  { "id" => 41, "parent" => 39, "name" => "North Forest 2" },
  { "id" => 42, "parent" => 39, "name" => "North Forest 3" },
  { "id" => 20, "parent" => 39, "name" => "North Forest 4" },
  { "id" => 43, "parent" => 39, "name" => "North Forest 5" },
  { "id" => 55, "parent" => 43, "name" => "Bandit's Gate" },
  { "id" => 56, "parent" => 43, "name" => "Bandit's Camp 1" },
  { "id" => 57, "parent" => 43, "name" => "Bandit's Camp 2" },
  { "id" => 58, "parent" => 43, "name" => "Prison" },
  { "id" => 65, "parent" => 43, "name" => "Bandit's Camp 3" },
  { "id" => 66, "parent" => 43, "name" => "Boss's Mansion" },
  { "id" => 69, "parent" => 43, "name" => "Working area" },
  { "id" => 45, "parent" => 44, "name" => "South Forest 1" },
  { "id" => 47, "parent" => 44, "name" => "South Forest 2" },
  { "id" => 48, "parent" => 44, "name" => "South Gate" },
  { "id" => 46, "parent" => 45, "name" => "Tavern Inside" },
  { "id" => 49, "parent" => 45, "name" => "Tavern Inside F2" },
  { "id" => 50, "parent" => 47, "name" => "Tent 1" },
  { "id" => 52, "parent" => 47, "name" => "Commander's Tent" },
  { "id" => 51, "parent" => 47, "name" => "Tent 2" },
  { "id" => 63, "parent" => 56, "name" => "House 1" },
  { "id" => 64, "parent" => 56, "name" => "House 2" },
  { "id" => 59, "parent" => 58, "name" => "Prison's Cave" },
  { "id" => 60, "parent" => 58, "name" => "Prison Lockups" },
  { "id" => 62, "parent" => 58, "name" => "Abandoned area" },
  { "id" => 61, "parent" => 60, "name" => "Hidden tunnel" },
  { "id" => 67, "parent" => 66, "name" => "Boss's Mansion F1" },
  { "id" => 68, "parent" => 66, "name" => "Boss's Mansion F2" }
]
