module CG

  POSES = {
    'AA' => [
      control({ :x => 500, :y => 250 }),
      layer(:hairback, 'PoseA_hair'),
      layer(:jacketback, 'PoseA_jacketA04', { :if => 'switch(jacket)' }),
      layer(:body, 'PoseA_bodyA'),
      layer(:panty, 'PoseA_panty', { :if => 'switch(panty)' }),
      layer(:bust, 'PoseA_bustA02'),
      layer(:camisole, 'PoseA_camisoleA02', { :if => 'switch(camisole)' }),
      layer(:skirt, 'PoseA_skirtA', { :if => 'switch(skirt)' }),
      layer(:jacket, 'PoseA_jacketA02', { :if => 'switch(jacket)' }),
      layer(:head),
      layer(:sweat, 'PoseA_sweat', { :if => 'attr(sweat)' }),
      layer(:red, 'PoseA_red', { :if => 'attr(red)' }),
      layer(:foot),
    ],
    'AB' => [
      control({ :x => 500, :y => 250 }),
      layer(:hairback, 'PoseA_hair'),
      layer(:jacketback, 'PoseA_jacketA04', { :if => 'switch(jacket)' }),
      layer(:body, 'PoseA_bodyB'),
      layer(:panty, 'PoseA_panty', { :if => 'switch(panty)' }),
      layer(:bust, 'PoseA_bustA02'),
      layer(:camisole, 'PoseA_camisoleA02', { :if => 'switch(camisole)' }),
      layer(:skirt, 'PoseA_skirtA', { :if => 'switch(skirt)' }),
      layer(:jacket, 'PoseA_jacketB02', { :if => 'switch(jacket)' }),
      layer(:head),
      layer(:sweat, 'PoseA_sweat', { :if => 'attr(sweat)' }),
      layer(:red, 'PoseA_red', { :if => 'attr(red)' }),
    ],
    'AC' => [
      control({ :x => 500, :y => 250 }),
      layer(:hairback, 'PoseA_hair'),
      layer(:body, 'PoseA_bodyC'),
      layer(:panty, 'PoseA_panty', { :if => 'switch(panty)' }),
      layer(:bust, 'PoseA_bustA02'),
      layer(:camisole, 'PoseA_camisoleC02', { :if => 'switch(camisole)' }),
      layer(:skirt, 'PoseA_skirtA', { :if => 'switch(skirt)' }),
      layer(:head),
      layer(:sweat, 'PoseA_sweat', { :if => 'attr(sweat)' }),
      layer(:red, 'PoseA_red', { :if => 'attr(red)' }),
    ],
    'AD' => [
      control({ :x => 470, :y => 255 }),
      layer(:hairback, 'PoseA_hair'),
      layer(:jacketback, 'PoseA_jacketA04', { :if => 'switch(jacket)' }),
      layer(:body, 'PoseA_bodyD'),
      layer(:panty, 'PoseA_panty', { :if => 'switch(panty)' }),
      layer(:bust, 'PoseA_bustA01'),
      layer(:camisole, 'PoseA_camisoleD', { :if => 'switch(camisole)' }),
      layer(:skirt, 'PoseA_skirtA', { :if => 'switch(skirt)' }),
      layer(:jacket, 'PoseA_jacketD', { :if => 'switch(jacket)' }),
      layer(:head),
      layer(:sweat, 'PoseA_sweat', { :if => 'attr(sweat)' }),
      layer(:red, 'PoseA_red', { :if => 'attr(red)' }),
    ],
    'AE' => [
      control({ :x => 500, :y => 250 }),
      layer(:hairback, 'PoseA_hair'),
      layer(:jacketback, 'PoseA_jacketA04', { :if => 'switch(jacket)' }),
      layer(:body, 'PoseA_bodyE'),
      layer(:panty, 'PoseA_panty', { :if => 'switch(panty)' }),
      layer(:bust, 'PoseA_bustA01'),
      layer(:camisole, 'PoseA_camisoleE', { :if => 'switch(camisole)' }),
      layer(:skirt, 'PoseA_skirtA', { :if => 'switch(skirt)' }),
      layer(:jacket, 'PoseA_jacketE', { :if => 'switch(jacket)' }),
      layer(:head),
      layer(:sweat, 'PoseA_sweat', { :if => 'attr(sweat)' }),
      layer(:red, 'PoseA_red', { :if => 'attr(red)' }),
    ],
    'BA' => [
      control({ :x => 500, :y => 250 }),
      layer(:body, 'PoseB_bodyA'),
      layer(:head),
      layer(:panty, 'PoseB_panty', { :if => 'switch(panty)' }),
      layer(:camisole, 'PoseB_camisoleA', { :if => 'switch(camisole)' }),
      layer(:skirt, 'PoseB_skirtA', { :if => 'switch(skirt)' }),
      layer(:jacket, 'PoseB_jacketA', { :if => 'switch(jacket)' }),
      layer(:hair, 'PoseB_hair'),
    ],
    'BB' => [
      control({ :x => 500, :y => 250 }),
      layer(:body, 'PoseB_bodyB'),
      layer(:head),
      layer(:panty, 'PoseB_Panty', { :if => 'switch(panty)' }),
      layer(:camisole, 'PoseB_CamisoleA', { :if => 'switch(camisole)' }),
      layer(:skirt, 'PoseB_SkirtB', { :if => 'switch(skirt)' }),
      layer(:jacketA, 'PoseB_jacketB01', { :if => 'switch(jacket) && !switch(skirt)' }),
      layer(:jacketB, 'PoseB_jacketB02', { :if => 'switch(jacket) && switch(skirt)' }),
      layer(:hair, 'PoseB_hair'),
    ],
    'CA' => [
      control({ :x => 500, :y => 250 }),
      layer(:hairback, 'PoseC_hair'),
      layer(:jacketback),
      layer(:body, 'PoseC_bodyA'),
      layer(:panty, 'PoseC_panty', { :if => 'switch(panty)' }),
      layer(:skirt, 'PoseC_skirtA', { :if => 'switch(skirt)' }),
      layer(:bust, 'PoseC_bust'),
      layer(:camisole, 'PoseC_camisoleA', { :if => 'switch(camisole)' }),
      layer(:jacket, 'PoseC_jacketA', { :if => 'switch(jacket)' }),
      layer(:head),
      layer(:sweat, 'PoseC_sweat', { :if => 'attr(sweat)' }),
      layer(:red, 'PoseC_red', { :if => 'attr(red)' }),
      layer(:foot),
    ],
    'CB' => [
      control({ :x => 500, :y => 250 }),
      layer(:hairback, 'PoseC_hair'),
      layer(:jacketback),
      layer(:body, 'PoseC_bodyB'),
      layer(:panty, 'PoseC_panty', { :if => 'switch(panty)' }),
      layer(:skirt, 'PoseC_skirtA', { :if => 'switch(skirt)' }),
      layer(:bust, 'PoseC_bust'),
      layer(:camisole, 'PoseC_camisoleA', { :if => 'switch(camisole)' }),
      layer(:jacket, 'PoseC_jacketB', { :if => 'switch(jacket)' }),
      layer(:head),
      layer(:sweat, 'PoseC_sweat', { :if => 'attr(sweat)' }),
      layer(:red, 'PoseC_red', { :if => 'attr(red)' }),
      layer(:foot),
    ],
    'DA' => [
      control({ :x => 500, :y => 250 }),
      layer(:hairback, 'PoseD_hair'),
      layer(:jacketback, 'PoseD_jacketback', { :if => 'switch(jacket)' }),
      layer(:body, 'PoseD_bodyA'),
      layer(:panty, 'PoseD_panty', { :if => 'switch(panty)' }),
      layer(:bust),
      layer(:camisole, 'PoseD_camisoleA', { :if => 'switch(camisole)' }),
      layer(:skirt, 'PoseD_skirtA', { :if => 'switch(skirt)' }),
      layer(:jacket, 'PoseD_jacketA', { :if => 'switch(jacket)' }),
      layer(:head),
      layer(:sweat, 'PoseD_sweat', { :if => 'attr(sweat)' }),
      layer(:red, 'PoseD_red', { :if => 'attr(red)' }),
      layer(:foot, 'PoseD_foot'),
    ],
  }

end
