module CG

  POSES = {
    'AA' => [
      control({ :x => 500, :y => 250 }),
      layer(:hand, 'PoseA_hand'),
      layer(:hairback, 'PoseA_hair'),
      layer(:jacketback, 'PoseA_jacketback01', { :if => 'switch(jacket)' }),
      layer(:body, 'PoseA_bodyA'),
      layer(:panty, 'PoseA_pantyA', { :if => 'switch(panty)' }),
      layer(:bust, 'PoseA_bustA01'),
      layer(:camisole, 'PoseA_camisoleA01', { :if => 'switch(camisole)' }),
      layer(:skirt, 'PoseA_skirtA', { :if => 'switch(skirt)' }),
      layer(:jacket, 'PoseA_jacketA01', { :if => 'switch(jacket)' }),
      layer(:head),
      layer(:sweat, 'PoseA_sweat', { :if => 'attr(sweat)' }),
      layer(:red, 'PoseA_red', { :if => 'attr(red)' }),
    ],
    'AB' => [
      control({ :x => 500, :y => 250 }),
      layer(:hand, 'PoseA_hand'),
      layer(:hairback, 'PoseA_hair'),
      layer(:jacketback, 'PoseA_jacketback01', { :if => 'switch(jacket)' }),
      layer(:body, 'PoseA_bodyB'),
      layer(:panty, 'PoseA_pantyB', { :if => 'switch(panty)' }),
      layer(:bust, 'PoseA_bustA01'),
      layer(:camisole, 'PoseA_camisoleB01', { :if => 'switch(camisole)' }),
      layer(:skirt, 'PoseA_skirtB', { :if => 'switch(skirt)' }),
      layer(:jacket, 'PoseA_jacketB01', { :if => 'switch(jacket)' }),
      layer(:head),
      layer(:sweat, 'PoseA_sweat', { :if => 'attr(sweat)' }),
      layer(:red, 'PoseA_red', { :if => 'attr(red)' }),
    ],
    'AC' => [
      control({ :x => 500, :y => 250 }),
      layer(:hairback, 'PoseA_hair'),
      layer(:jacketback),
      layer(:body, 'PoseA_bodyC'),
      layer(:panty, 'PoseA_panty', { :if => 'switch(panty)' }),
      layer(:bust, 'PoseA_bustA02'),
      layer(:camisole, 'PoseA_camisoleC02', { :if => 'switch(camisole)' }),
      layer(:skirt, 'PoseA_skirtA', { :if => 'switch(skirt)' }),
      layer(:jacket),
      layer(:head),
      layer(:sweat, 'PoseA_sweat', { :if => 'attr(sweat)' }),
      layer(:red, 'PoseA_red', { :if => 'attr(red)' }),
    ],
    'AD' => [
      control({ :x => 470, :y => 255 }),
      layer(:hairback, 'PoseA_hair'),
      layer(:skirtback, 'PoseA_skirtbackD', { :if => 'switch(skirt)' }),
      layer(:jacketback, 'PoseA_jacketA04', { :if => 'switch(jacket)' }),
      layer(:body, 'PoseA_bodyD'),
      layer(:panty, 'PoseA_panty', { :if => 'switch(panty)' }),
      layer(:bust, 'PoseA_bustA01'),
      layer(:camisole, 'PoseA_camisoleD', { :if => 'switch(camisole)' }),
      layer(:skirt, 'PoseA_skirtD', { :if => 'switch(skirt)' }),
      layer(:jacket, 'PoseA_jacketD', { :if => 'switch(jacket)' }),
      layer(:head),
      layer(:sweat, 'PoseA_sweat', { :if => 'attr(sweat)' }),
      layer(:red, 'PoseA_red', { :if => 'attr(red)' }),
    ],
    'AE' => [
      control({ :x => 500, :y => 250 }),
      layer(:hairback, 'PoseA_hair'),
      layer(:skirtback, 'PoseA_skirtbackE', { :if => 'switch(skirt)' }),
      layer(:jacketback, 'PoseA_jacketA04', { :if => 'switch(jacket)' }),
      layer(:body, 'PoseA_bodyE'),
      layer(:panty, 'PoseA_panty', { :if => 'switch(panty)' }),
      layer(:bust, 'PoseA_bustA01'),
      layer(:camisole, 'PoseA_camisoleE', { :if => 'switch(camisole)' }),
      layer(:skirt, 'PoseA_skirtE', { :if => 'switch(skirt)' }),
      layer(:jacket, 'PoseA_jacketE', { :if => 'switch(jacket)' }),
      layer(:head),
      layer(:sweat, 'PoseA_sweat', { :if => 'attr(sweat)' }),
      layer(:red, 'PoseA_red', { :if => 'attr(red)' }),
    ],
    'BA' => [
      control({ :x => 500, :y => 250 }),
      layer(:head),
      layer(:body, 'PoseB_bodyA'),
      layer(:panty, 'PoseB_panty', { :if => 'switch(panty)' }),
      layer(:bust),
      layer(:camisole, 'PoseB_camisoleA', { :if => 'switch(camisole)' }),
      layer(:skirt, 'PoseB_skirtA', { :if => 'switch(skirt)' }),
      layer(:jacket, 'PoseB_jacketA', { :if => 'switch(jacket)' }),
      layer(:hair, 'PoseB_hair'),
      layer(:sweat),
      layer(:red),
    ],
    'BB' => [
      control({ :x => 500, :y => 250 }),
      layer(:head),
      layer(:body, 'PoseB_bodyB'),
      layer(:panty, 'PoseB_panty', { :if => 'switch(panty)' }),
      layer(:bust),
      layer(:camisole, 'PoseB_camisoleA', { :if => 'switch(camisole)' }),
      layer(:skirt, 'PoseB_skirtB', { :if => 'switch(skirt)' }),
      layer(:jacket, 'PoseB_jacketB02', { :if => 'switch(jacket)' }),
      layer(:jacket),
      layer(:hair, 'PoseB_hair'),
      layer(:sweat),
      layer(:red),
    ],
    'CA' => [
      control({ :x => 500, :y => 250 }),
      layer(:hairback, 'PoseC_hair'),
      layer(:body, 'PoseC_bodyA'),
      layer(:jacketback, 'PoseC_JacketBack', { :if => 'switch(jacket)' }),
      layer(:panty, 'PoseC_panty', { :if => 'switch(panty)' }),
      layer(:skirt, 'PoseC_skirt', { :if => 'switch(skirt)' }),
      layer(:camisole, 'PoseC_camisole', { :if => 'switch(camisole)' }),
      layer(:jacket, 'PoseC_jacket', { :if => 'switch(jacket)' }),
      layer(:head),
      layer(:sweat, 'PoseC_sweat', { :if => 'attr(sweat)' }),
      layer(:red, 'PoseC_red', { :if => 'attr(red)' }),
    ],
    'CB' => [
      control({ :x => 500, :y => 250 }),
      layer(:hairback, 'PoseC_hair'),
      layer(:body, 'PoseC_bodyA'),
      layer(:jacketback, 'PoseC_JacketBack', { :if => 'switch(jacket)' }),
      layer(:panty, 'PoseC_panty', { :if => 'switch(panty)' }),
      layer(:skirt, 'PoseC_skirt', { :if => 'switch(skirt)' }),
      layer(:camisole, 'PoseC_camisole', { :if => 'switch(camisole)' }),
      layer(:jacket, 'PoseC_jacket', { :if => 'switch(jacket)' }),
      layer(:head),
      layer(:sweat, 'PoseC_sweat', { :if => 'attr(sweat)' }),
      layer(:red, 'PoseC_red', { :if => 'attr(red)' }),
    ],
    'DA' => [
      control({ :x => 500, :y => 250 }),
      layer(:shadow, 'PoseD_shadow'),
      layer(:hairback, 'PoseD_backhair'),
      layer(:jacketback, 'PoseD_jacketback', { :if => 'switch(jacket)' }),
      layer(:body, 'PoseD_bodyA'),
      layer(:panty, 'PoseD_panty', { :if => 'switch(panty)' }),
      layer(:camisole, 'PoseD_camisole', { :if => 'switch(camisole)' }),
      layer(:skirt, 'PoseD_skirt', { :if => 'switch(skirt)' }),
      layer(:jacket, 'PoseD_jacket', { :if => 'switch(jacket)' }),
      layer(:head),
      layer(:fronthair, 'PoseD_FrontHair'),
      layer(:sweat, 'PoseD_sweat', { :if => 'attr(sweat)' }),
      layer(:red, 'PoseD_red', { :if => 'attr(red)' }),
    ],
  }

end
