module CG

  SHAKES = {
    'AA' => [
      sfx('Audio/SE/poyoyon', 70, 90),
      layer(:bust, 'PoseA_bustA01'),
      layer(:camisole, 'PoseA_camisoleA01', { :if => 'switch(camisole)' }),
      layer(:jacket, 'PoseA_jacketA01', { :if => 'switch(jacket)' }),
      wait(5),
      layer(:bust, 'PoseA_bustA02'),
      layer(:camisole, 'PoseA_camisoleA02', { :if => 'switch(camisole)' }),
      layer(:jacket, 'PoseA_jacketA02', { :if => 'switch(jacket)' }),
      wait(2),
      layer(:bust, 'PoseA_bustA03'),
      layer(:camisole, 'PoseA_camisoleA03', { :if => 'switch(camisole)' }),
      layer(:jacket, 'PoseA_jacketA03', { :if => 'switch(jacket)' }),
      wait(2),
      layer(:bust, 'PoseA_bustA02'),
      layer(:camisole, 'PoseA_camisoleA02', { :if => 'switch(camisole)' }),
      layer(:jacket, 'PoseA_jacketA02', { :if => 'switch(jacket)' }),
      wait(3),
      layer(:bust, 'PoseA_bustA03'),
      layer(:camisole, 'PoseA_camisoleA03', { :if => 'switch(camisole)' }),
      layer(:jacket, 'PoseA_jacketA03', { :if => 'switch(jacket)' }),
      wait(3),
      layer(:bust, 'PoseA_bustA02'),
      layer(:camisole, 'PoseA_camisoleA02', { :if => 'switch(camisole)' }),
      layer(:jacket, 'PoseA_jacketA02', { :if => 'switch(jacket)' }),
    ],
    'AB' => [
      sfx('Audio/SE/poyoyon', 70, 90),
      layer(:bust, 'PoseA_bustA01'),
      layer(:camisole, 'PoseA_camisoleA01', { :if => 'switch(camisole)' }),
      layer(:jacket, 'PoseA_jacketB01', { :if => 'switch(jacket)' }),
      wait(5),
      layer(:bust, 'PoseA_bustA02'),
      layer(:camisole, 'PoseA_camisoleA02', { :if => 'switch(camisole)' }),
      layer(:jacket, 'PoseA_jacketB02', { :if => 'switch(jacket)' }),
      wait(2),
      layer(:bust, 'PoseA_bustA03'),
      layer(:camisole, 'PoseA_camisoleA03', { :if => 'switch(camisole)' }),
      layer(:jacket, 'PoseA_jacketB03', { :if => 'switch(jacket)' }),
      wait(2),
      layer(:bust, 'PoseA_bustA02'),
      layer(:camisole, 'PoseA_camisoleA02', { :if => 'switch(camisole)' }),
      layer(:jacket, 'PoseA_jacketB02', { :if => 'switch(jacket)' }),
      wait(3),
      layer(:bust, 'PoseA_bustA03'),
      layer(:camisole, 'PoseA_camisoleA03', { :if => 'switch(camisole)' }),
      layer(:jacket, 'PoseA_jacketB03', { :if => 'switch(jacket)' }),
      wait(3),
      layer(:bust, 'PoseA_bustA02'),
      layer(:camisole, 'PoseA_camisoleA02', { :if => 'switch(camisole)' }),
      layer(:jacket, 'PoseA_jacketB02', { :if => 'switch(jacket)' }),
    ],
    'AC' => [
      sfx('Audio/SE/poyoyon', 70, 90),
      layer(:bust, 'PoseA_bustA01'),
      layer(:camisole, 'PoseA_camisoleC01', { :if => 'switch(camisole)' }),
      wait(5),
      layer(:bust, 'PoseA_bustA02'),
      layer(:camisole, 'PoseA_camisoleC02', { :if => 'switch(camisole)' }),
      wait(2),
      layer(:bust, 'PoseA_bustA03'),
      layer(:camisole, 'PoseA_camisoleC03', { :if => 'switch(camisole)' }),
      wait(2),
      layer(:bust, 'PoseA_bustA02'),
      layer(:camisole, 'PoseA_camisoleC02', { :if => 'switch(camisole)' }),
      wait(3),
      layer(:bust, 'PoseA_bustA03'),
      layer(:camisole, 'PoseA_camisoleC03', { :if => 'switch(camisole)' }),
      wait(3),
      layer(:bust, 'PoseA_bustA02'),
      layer(:camisole, 'PoseA_camisoleC02', { :if => 'switch(camisole)' }),
    ],
  }

end
