#!/usr/bin/ruby
require 'zlib'

# Scripts are organized as an array of entries
# Each entry is another array with three elements:
# 0 random number?
# 1 script name
# 2 compressed script source

class Writer
  def self.write_file(layout_file, output_file)
    scripts = self.compile_scripts(layout_file)
    File.open(output_file, "wb") { |f| Marshal.dump(scripts, f) }
  end

  def self.compile_scripts(layout_file)
    scripts = []
    File.open(layout_file).each(sep="\n") do |line|
      name, script_file = line.strip().split("|")
      if File.exists?(script_file)
        scripts.push([rand(99999999), name, Zlib::Deflate.deflate(File.read(script_file))])
      end
    end
    return scripts
  end
end

if ARGV.length > 1
  Writer.write_file(ARGV[0], ARGV[1])
end
