1 0 9 Yuuki.pose("AA").face("AD01").sweat(0)
1 0 10 Yuuki.slide
1 0 11
1 0 12
1 0 13 Yuuki.pose("AA").face("AD01").sweat(0)
1 0 14 Yuuki.shake
1 0 15
1 0 16
1 0 17 Yuuki.pose("AB").face("AD02").sweat(0)
1 0 18

1 0 22 Yuuki.clear
1 0 23

1 0 34 Yuuki.pose("AA").face("AD01").sweat(0)
1 0 35 Yuuki.slide
1 0 36
1 0 37
1 0 38 Yuuki.pose("AA").face("AD01").sweat(0)
1 0 39 Yuuki.shake
1 0 40
1 0 41
1 0 42 Yuuki.pose("AC").face("AD02").sweat(0)
1 0 43

1 0 47 Yuuki.clear
1 0 48
