4 0 7 Yuuki.pose("BA").face("BA01").sweat(0).blush(0)
4 0 8

4 0 10 Yuuki.pose("BB").face("BA01").sweat(0).blush(0)
4 0 11
4 0 12
4 0 13

4 0 17 Yuuki.pose("AB").face("AC01").sweat(0).blush(1)
4 0 18 Yuuki.shake
4 0 19
4 0 20

4 0 23 Yuuki.pose("AB").face("AD07").sweat(0).blush(1)
4 0 24
4 0 25
4 0 26

4 0 31 Yuuki.pose("AB").face("AD03").sweat(0).blush(1)
4 0 32
4 0 33
4 0 34

4 0 38 Yuuki.clear
4 0 39
