


6 1 0 $pose = Pose.new("A","B","E03",1,0)
6 1 1 $pose.slide
6 1 2 $pose.clear
6 1 3 $pose = nil
6 1 4 $pose = Pose.new("A","B","E03",1,0)
6 1 5 $pose.shake

6 1 28 $pose.clear
6 1 29 $pose = nil
6 1 30 $pose = Pose.new("A","B","E05",0,0)
6 1 31 $pose.pop

6 1 35 $pose.clear
6 1 36 $pose = nil

6 1 39 $pose = Pose.new("A","A","E01",0,0)
6 1 40 $pose.slide

6 1 53 $pose.clear
6 1 54 $pose = nil
6 1 55 $pose = Pose.new("A","A","E02",0,0)
6 1 56 $pose.shake

6 1 59 $pose.clear
6 1 60 $pose = nil
6 1 61 $pose = Pose.new("A","A","E03",0,0)
6 1 62 $pose.pop

6 1 77 $pose.clear
6 1 78 $pose = nil
6 1 79 $pose = Pose.new("A","A","E06",0,0)
6 1 80 $pose.pop

6 1 84 $pose.clear
6 1 85 $pose = nil
6 1 86 $pose = Pose.new("A","A","E03",0,0)
6 1 87 $pose.pop

6 1 92 $pose.clear
6 1 93 $pose = nil
6 1 94 $pose = Pose.new("A","A","E02",0,0)
6 1 95 $pose.pop

6 1 108 $pose.clear
6 1 109 $pose = nil
6 1 110 $pose = Pose.new("A","A","E05",1,0)
6 1 111 $pose.shake

6 1 129 $pose.clear
6 1 130 $pose = nil
6 1 131 $pose = Pose.new("A","A","E06",0,0)
6 1 132 $pose.pop

6 1 135 $pose.clear
6 1 136 $pose = nil
6 1 137 $pose = Pose.new("A","A","E07",0,0)
6 1 138 $pose.pop

6 1 154 $pose.clear
6 1 155 $pose = nil
6 1 156 $pose = Pose.new("A","A","E05",0,0)
6 1 157 $pose.pop

6 1 162 $pose.clear
6 1 163 $pose = nil
6 1 164 $pose = Pose.new("A","A","E06",1,1)
6 1 165 $pose.pop

6 1 168 $pose.clear
6 1 169 $pose = nil
6 1 170 $pose = Pose.new("A","A","E07",1,1)
6 1 171 $pose.pop

6 1 181 $pose.clear
6 1 182 $pose = nil
6 1 183 $pose = Pose.new("A","A","E06",1,1)
6 1 184 $pose.pop

6 1 187 $pose.clear
6 1 188 $pose = nil
6 1 189 $pose = Pose.new("A","A","E07",1,1)
6 1 190 $pose.pop

6 1 196 $pose.clear
6 1 197 $pose = nil
6 1 198 $pose = Pose.new("A","A","E06",0,1)
6 1 199 $pose.pop

6 1 202 $pose.clear
6 1 203 $pose = nil
6 1 204 $pose = Pose.new("A","A","E03",0,1)
6 1 205 $pose.pop

6 1 215 $pose.clear
6 1 216 $pose = nil
6 1 217 $pose = Pose.new("A","A","E06",0,0)
6 1 218 $pose.pop

6 1 223 $pose.clear
6 1 224 $pose = nil
6 1 225 $pose = Pose.new("A","A","E02",0,0)
6 1 226 $pose.shake

6 1 230 $pose.clear
6 1 231 $pose = nil
6 1 232 $pose = Pose.new("A","A","E03",0,0)
6 1 233 $pose.pop

6 1 249 $pose.clear
6 1 250 $pose = nil
6 1 251 $pose = Pose.new("A","A","E02",0,0)
6 1 252 $pose.pop

6 1 255 $pose.clear
6 1 256 $pose = nil

6 1 260 $pose = Pose.new("A","A","A03",1,0)
6 1 261 $pose.slide

6 1 268 $pose.clear
6 1 269 $pose = nil
6 1 270 $pose = Pose.new("A","A","D07",1,1)
6 1 271 $pose.pop

6 1 279 $pose.clear
6 1 280 $pose = nil

6 1 288 $pose = Pose.new("D","A","E02",1,0)
6 1 289 $pose.slide

6 1 295 $pose.clear
6 1 296 $pose = nil
6 1 297 $pose = Pose.new("D","A","E01",1,0)
6 1 298 $pose.pop

6 1 301 $pose.clear
6 1 302 $pose = nil

6 2 6 $pose = Pose.new("A","A","E01",0,0)
6 2 7 $pose.slide

6 2 20 $pose.clear
6 2 21 $pose = nil
6 2 22 $pose = Pose.new("A","A","E02",0,0)
6 2 23 $pose.shake

6 2 26 $pose.clear
6 2 27 $pose = nil
6 2 28 $pose = Pose.new("A","A","E03",0,0)
6 2 29 $pose.pop

6 2 44 $pose.clear
6 2 45 $pose = nil
6 2 46 $pose = Pose.new("A","A","E06",0,0)
6 2 47 $pose.pop

6 2 51 $pose.clear
6 2 52 $pose = nil
6 2 53 $pose = Pose.new("A","A","E03",0,0)
6 2 54 $pose.pop

6 2 59 $pose.clear
6 2 60 $pose = nil
6 2 61 $pose = Pose.new("A","A","E02",0,0)
6 2 62 $pose.pop

6 2 75 $pose.clear
6 2 76 $pose = nil
6 2 77 $pose = Pose.new("A","A","E05",1,0)
6 2 78 $pose.shake

6 2 96 $pose.clear
6 2 97 $pose = nil
6 2 98 $pose = Pose.new("A","A","E06",0,0)
6 2 99 $pose.pop

6 2 102 $pose.clear
6 2 103 $pose = nil
6 2 104 $pose = Pose.new("A","A","E07",0,0)
6 2 105 $pose.pop

6 2 121 $pose.clear
6 2 122 $pose = nil
6 2 123 $pose = Pose.new("A","A","E05",0,0)
6 2 124 $pose.pop

6 2 129 $pose.clear
6 2 130 $pose = nil
6 2 131 $pose = Pose.new("A","A","E06",1,1)
6 2 132 $pose.pop

6 2 135 $pose.clear
6 2 136 $pose = nil
6 2 137 $pose = Pose.new("A","A","E07",1,1)
6 2 138 $pose.pop

6 2 148 $pose.clear
6 2 149 $pose = nil
6 2 150 $pose = Pose.new("A","A","E06",1,1)
6 2 151 $pose.pop

6 2 154 $pose.clear
6 2 155 $pose = nil
6 2 156 $pose = Pose.new("A","A","E07",1,1)
6 2 157 $pose.pop

6 2 163 $pose.clear
6 2 164 $pose = nil
6 2 165 $pose = Pose.new("A","A","E06",0,1)
6 2 166 $pose.pop

6 2 169 $pose.clear
6 2 170 $pose = nil
6 2 171 $pose = Pose.new("A","A","E03",0,1)
6 2 172 $pose.pop

6 2 182 $pose.clear
6 2 183 $pose = nil
6 2 184 $pose = Pose.new("A","A","E06",0,0)
6 2 185 $pose.pop

6 2 190 $pose.clear
6 2 191 $pose = nil
6 2 192 $pose = Pose.new("A","A","E02",0,0)
6 2 193 $pose.shake

6 2 197 $pose.clear
6 2 198 $pose = nil
6 2 199 $pose = Pose.new("A","A","E03",0,0)
6 2 200 $pose.pop

6 2 216 $pose.clear
6 2 217 $pose = nil
6 2 218 $pose = Pose.new("A","A","E02",0,0)
6 2 219 $pose.pop

6 2 222 $pose.clear
6 2 223 $pose = nil

6 2 227 $pose = Pose.new("A","A","A03",1,0)
6 2 228 $pose.slide

6 2 235 $pose.clear
6 2 236 $pose = nil
6 2 237 $pose = Pose.new("A","A","D07",1,1)
6 2 238 $pose.pop

6 2 246 $pose.clear
6 2 247 $pose = nil

6 2 257 $pose = Pose.new("D","A","E02",1,0)
6 2 258 $pose.slide

6 2 264 $pose.clear
6 2 265 $pose = nil
6 2 266 $pose = Pose.new("D","A","E01",1,0)
6 2 267 $pose.pop

6 2 270 $pose.clear
6 2 271 $pose = nil



1 1 0 $pose = Pose.new("A","B","A03",1,0)
1 1 1 $pose.slide

1 1 4 $pose.clear
1 1 5 $pose = nil



2 1 0 $pose = Pose.new("A","B","B01",1,0)
2 1 1 $pose.slide
2 1 2 $pose.clear
2 1 3 $pose = nil
2 1 4 $pose = Pose.new("A","B","B01",1,0)
2 1 5 $pose.shake

2 1 8 $pose.clear
2 1 9 $pose = nil






